[tool.poetry]
name = "autorizfirst"
version = "0.1.0"
description = "First authorizade pacache"
authors = ["alex"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.118.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
