"""empty message

Revision ID: a2a8fcb03f0c
Revises: ce400e8d6053
Create Date: 2025-08-19 22:25:23.862107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a8fcb03f0c'
down_revision: Union[str, Sequence[str], None] = 'ce400e8d6053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
